select 
BARCODE,TRKDATE,OPERATOR,MSGTYPE,CAUSAL,TEST_FLAG,PHASE_AT,ARRIVETIMESTAMP,STATUS,TRACK_OFFICE,MTF_MTFID,OFFICE_OTHER,DATE_OTHER,ALIAS,ISOCODE,PHASE_OTHER,DT_DISPBARCODE,DT_TRKDATE,MECC,IDMECC,FIRST_OCR_DATE,LAST_OCR_DATE,AREADEST,BT_BUNDBARCODE,BT_TRKDATE,LDT_LDID,LDT_TRKDATE,MSID,MSNAME,FDNUM,DELREASON,RECID,RECNAME,DELEGNAME,DOCTYPE,DOCID,DOCAGENCY,DOCEXPTIME,CAUNOTIF,NUMATTO,DATATTO,CASACOMUNALE,COMUNE,ZONE_ID,SUBZONE_ID,ONER_DOG,DIR_POST,LAT_GPS,LONG_GPS,DELIVERY_ACTION,CHIAVECLIENTE,TIPOCHIAVE,CHIAVEOPER,CANALE,GUID,SERV_GUID,CUSTCODE,DWNLD,DSCOP,TIPOP,REALTIME,ANUL,QR_CODE,CUST_SPED,IDSPED,ISOCODE_MITT,NVICINO,DEND,EMSEVT,UPUCODE,ID_CIVICO,CANCELLO,LUOGO,ODD,SIM,ANDROID,NOTA,WA,PIST,PROC,UGIU,TIPO23L,CODICECANCAD,TIPO_SERVIZIO,HFUNCTION,PROGRESSIVOAR,PROGAUTOROUTE,EVENTOCRITICO,IDEVENTOCRITICO,CHIUSOPERFERIE,CREATA23LDIGITALE,FASCIAORACONSDA,FASCIAORACONSA,FE,LUOGO_SEL_CONS,MOTIVAZIONE_FE,MOD_RIMBORSO,COMM_VAGLIA_INT,FLG_IOSS_NOIOSS,FLG_NOIOSS_NORISC,STATO_APPUNTAMENTO,OFFICE_INESITO,DATA_LAVORAZIONE,FLAG_GG_MAZZETTO,DATA_TENT_RECAPITO,DATA_DISP_RITIRO,TIPO_SBLOCCO,IIL_ESITO,IIL_FONTE,IIL_PROVINCIA,IIL_COMUNE,IIL_INDIRIZZO,IIL_CAP,IIL_PAESEESTERO,OFFICE_ORIG,OFFICE_SOST,REROUTING_FUN,MOTIVO_BLOCCO,DACCATTO,PROVDEST,EXP_TIME_REC_PROG,ORIGINEVENTO,CONTOCONTRATT,CHIAVEFILE,NOMEFILE,DATARENDICONT,CANALERENDICONT,MPT_MPEC,USCITA
from starown.mailpiece_tracks t
where 1=1
--and t.causal in ('AEE', 'EXI', 'UAR')
AND trkdate > trunc(sysdate) -1
;

 